### ISSUE TITLE
API key usage tutorials?

### ISSUE THREAD

**Issue by jGaboardi** [walkerke/pygris#6]
@walkerke Thanks for all the awesome stuff you do with `pygris`, `tigris`, `tidycensus`, etc.!

One of colleagues (cc @brelsford) is mentoring a PhD student who has been using `tidycensus` but running into issues with her census API key for several weeks. Are there any intro-level resources to understand API key usage that you can recommend we share with here, particularly for the US census?

cc @ljwolf @knaaptime @jvtcl

**Comment by walkerke** [comment]
Thanks @jGaboardi!  Likewise, I've been promoting your work (spopt in particular) quite a lot recently.  

About the API key: 
* As of tidycensus v1.3, an API key is no longer required, though you'll hit a limit of 500 queries per day.  If you are having API key issues but need to do some one-off work, you can remove the `CENSUS_API_KEY` line from your `.Renviron` file.  
* In 90%+ percent of cases where I've helped users debug this, they have entered the wrong API key accidentally (e.g. cutting off some characters).  I would double-check that.  
* In some cases, however (see https://github.com/walkerke/tidycensus/issues/160) the API key mysteriously does not work sometimes, but works other times.  I have never experienced this issue and neither has Matt (my co-author) so we've had difficulty debugging it.  I have occasionally seen this issue pop up when users are on a shared server version of R that is potentially hitting the Census API quite a lot.  

There is a bit more on this in this doc: https://www.census.gov/content/dam/Census/data/developers/api-user-guide/api-guide.pdf (see the section on "Query Limits").  They mention that issues can arise if lots of queries appear to be coming from a shared IP address (e.g. within the same organization), so that might be something to look into.

**Comment by jGaboardi** [comment]
Awesome! I will pass the info along! Thanks again for taking the time to write this up. I am sure it will be useful for more folks.
